[versions]
# Android and Gradle
gradlePlugin = "8.13.2"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"

# AndroidX Core
appcompat = "1.7.1"
material = "1.13.0"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"

# another versions of webkit has random crashes
webkit = "1.12.1"


coreKtx = "1.17.0"
coreSplashscreen = "1.2.0"
legacySupportV4 = "1.0.0"

# AndroidX Work
workRuntime = "2.11.1"
workRxjava = "2.11.1"
workMultiprocess = "2.11.1"

# AndroidX Fragment
fragmentKtx = "1.8.9"

# AndroidX Concurrent
concurrentFutures = "1.3.0"

# AndroidX Lifecycle
lifecycleExtensions = "2.2.0"
lifecycleCompiler = "2.10.0"
lifecycleCommonJava8 = "2.10.0"
lifecycleLivedata = "2.10.0"
lifecycleViewmodel = "2.10.0"

# AndroidX Room
room = "2.8.4"

# AndroidX Arch Core
archCore = "2.2.0"

# Dagger2
dagger = "2.59"

# OkHttp
okhttp = "5.2.1" #after update error: abstract classes cant be instantiated

# Retrofit
retrofit = "3.0.0"

# RxJava and RxAndroid
rxjava3 = "3.1.12"
rxandroid3 = "3.0.2"

# Other Dependencies
glide = "5.0.5"
youtubedl = "0.18.1-alexch33-3"
ffmpegKit = "2.1.0"

# version change can break build
jsoup = "1.21.1"

timeago = "4.2.0"
persistentCookieJar = "1.0.1"
kotlinxSerializationJson = "1.10.0"
kotlinxSerializationCore = "1.10.0"

# Media3
media3 = "1.9.1"

# Testing
testRunner = "1.1.0"
junit = "4.13.2"
espresso = "3.0.2"
mockito = "5.21.0"
mockitoKotlin = "1.6.0"
androidxTestJunit = "1.3.0"
androidxTestEspresso = "3.7.0"
androidxTestEspressoIntents = "3.7.0"

# Code coverage and quality
jacoco = "0.8.1"
coveralls = "2.12.2"
desugarJdk = "2.1.5"

# NDK
ndk = "27.3.13750724"

# Build SDK versions
minSdk = "24"
targetSdk = "36"
jvmToolchain = "21"

# Go
goVersion = "1.25.0"

[libraries]
# Android and Gradle
gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugin" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk7", version.ref = "kotlin" }
kotlin-allopen = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
ksp-plugin = { module = "com.google.devtools.ksp:symbol-processing-gradle-plugin", version.ref = "ksp" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

# AndroidX Core
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
webkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
coreSplashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
legacySupportV4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }

# AndroidX Work
workRuntimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntime" }
workRxjava3 = { module = "androidx.work:work-rxjava3", version.ref = "workRxjava" }
workMultiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workMultiprocess" }

# AndroidX Fragment
fragmentKtx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }

# AndroidX Concurrent
concurrentFuturesKtx = { module = "androidx.concurrent:concurrent-futures-ktx", version.ref = "concurrentFutures" }

# AndroidX Lifecycle
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycleCompiler = { module = "androidx.lifecycle:lifecycle-compiler", version.ref = "lifecycleCompiler" }
lifecycleCommonJava8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
lifecycleLivedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedata" }
lifecycleViewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodel" }

# AndroidX Room
roomRuntime = { module = "androidx.room:room-runtime", version.ref = "room" }
roomCompiler = { module = "androidx.room:room-compiler", version.ref = "room" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "room" }
roomRxjava3 = { module = "androidx.room:room-rxjava3", version.ref = "room" }
roomGuava = { module = "androidx.room:room-guava", version.ref = "room" }

# AndroidX Arch Core
archCoreTesting = { module = "androidx.arch.core:core-testing", version.ref = "archCore" }

# Dagger2
daggerRuntime = { module = "com.google.dagger:dagger", version.ref = "dagger" }
daggerAndroid = { module = "com.google.dagger:dagger-android", version.ref = "dagger" }
daggerAndroidSupport = { module = "com.google.dagger:dagger-android-support", version.ref = "dagger" }
daggerCompiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger" }
daggerAndroidProcessor = { module = "com.google.dagger:dagger-android-processor", version.ref = "dagger" }

# OkHttp
okHttpRuntime = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okHttpLogging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }

# Retrofit
retrofitRuntime = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofitGson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofitRxjava3 = { module = "com.squareup.retrofit2:adapter-rxjava3", version.ref = "retrofit" }

# RxJava and RxAndroid
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3" }
rxandroid3 = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid3" }

# Glide
glideRuntime = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

# Other Dependencies
youtubedl = { module = "io.github.alexch33:youtubedl-android", version.ref = "youtubedl" }
ffmpegKit = { module = "com.antonkarpenko:ffmpeg-kit-full-gpl", version.ref = "ffmpegKit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
timeago = { module = "com.github.marlonlom:timeago", version.ref = "timeago" }
persistentCookieJar = { module = "com.github.franmontiel:PersistentCookieJar", version.ref = "persistentCookieJar" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlinxSerializationCore = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerializationCore" }

# Media3
media3Exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
media3ExoplayerDash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
media3ExoplayerHls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3" }
media3ExoplayerRtsp = { module = "androidx.media3:media3-exoplayer-rtsp", version.ref = "media3" }
media3Ui = { module = "androidx.media3:media3-ui", version.ref = "media3" }
media3Extractor = { module = "androidx.media3:media3-extractor", version.ref = "media3" }
media3Database = { module = "androidx.media3:media3-database", version.ref = "media3" }
media3Decoder = { module = "androidx.media3:media3-decoder", version.ref = "media3" }
media3Datasource = { module = "androidx.media3:media3-datasource", version.ref = "media3" }
media3Common = { module = "androidx.media3:media3-common", version.ref = "media3" }
media3DatasourceOkhttp = { module = "androidx.media3:media3-datasource-okhttp", version.ref = "media3" }

# Testing
testRunner = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
junit = { module = "junit:junit", version.ref = "junit" }
mockitoCore = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoAndroid = { module = "org.mockito:mockito-android", version.ref = "mockito" }
mockitoKotlin = { module = "com.nhaarman:mockito-kotlin", version.ref = "mockitoKotlin" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
espressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidxTestEspressoIntents" }

# Code Coverage
desugarJdk = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugarJdk" }
coverallsPlugin = { module = "org.kt3k.gradle.plugin:coveralls-gradle-plugin", version.ref = "coveralls" }

[bundles]
room = ["roomRuntime", "roomKtx", "roomRxjava3", "roomGuava"]
dagger = ["daggerRuntime", "daggerAndroid", "daggerAndroidSupport"]
okhttp = ["okHttpRuntime", "okHttpLogging"]
retrofit = ["retrofitRuntime", "retrofitGson", "retrofitRxjava3"]
rxjava3 = ["rxjava3", "rxandroid3"]
media3 = ["media3Exoplayer", "media3ExoplayerDash", "media3ExoplayerHls", "media3ExoplayerRtsp", "media3Ui", "media3Extractor", "media3Database", "media3Decoder", "media3Datasource", "media3Common", "media3DatasourceOkhttp"]
lifecycle = ["lifecycleExtensions", "lifecycleCommonJava8", "lifecycleLivedata", "lifecycleViewmodel"]
testing = ["junit", "mockitoCore", "mockitoAndroid", "mockitoKotlin", "espressoCore", "espressoIntents"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
coveralls = { id = "com.github.kt3k.coveralls", version.ref = "coveralls" }
